-- MySQL Script generated by MySQL Workbench
-- Tue May  6 20:21:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `libreria` ;

-- -----------------------------------------------------
-- Schema libreria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `libreria` ;

-- -----------------------------------------------------
-- Table `libreria`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`autor` ;

CREATE TABLE IF NOT EXISTS `libreria`.`autor` (
  `AutorID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `Nacionalidad` VARCHAR(50) NULL DEFAULT NULL,
  `FechaNacimiento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`AutorID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`cliente` ;

CREATE TABLE IF NOT EXISTS `libreria`.`cliente` (
  `ClienteID` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `Direccion` VARCHAR(255) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ClienteID`),
  UNIQUE INDEX `Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria`.`libros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`libros` ;

CREATE TABLE IF NOT EXISTS `libreria`.`libros` (
  `LibroID` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(255) NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `FechaPublicacion` DATE NULL DEFAULT NULL,
  `AutorID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`LibroID`),
  INDEX `AutorID` (`AutorID` ASC) VISIBLE,
  CONSTRAINT `libros_ibfk_1`
    FOREIGN KEY (`AutorID`)
    REFERENCES `libreria`.`autor` (`AutorID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libreria`.`ventas` ;

CREATE TABLE IF NOT EXISTS `libreria`.`ventas` (
  `VentaID` INT NOT NULL AUTO_INCREMENT,
  `ClienteID` INT NULL DEFAULT NULL,
  `LibroID` INT NULL DEFAULT NULL,
  `Cantidad` INT NOT NULL,
  `FechaVenta` DATE NOT NULL,
  PRIMARY KEY (`VentaID`),
  INDEX `ClienteID` (`ClienteID` ASC) VISIBLE,
  INDEX `LibroID` (`LibroID` ASC) VISIBLE,
  CONSTRAINT `ventas_ibfk_1`
    FOREIGN KEY (`ClienteID`)
    REFERENCES `libreria`.`cliente` (`ClienteID`),
  CONSTRAINT `ventas_ibfk_2`
    FOREIGN KEY (`LibroID`)
    REFERENCES `libreria`.`libros` (`LibroID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
